export const metadata = {
    title: "Estudio",
    description:"Generated by Akairo S.A.S",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}